### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by CValentinTraverso** [Chevifier/QuestManager#10]
In quest_manager all the signals are declared:

signal quest_completed(quest_name)
signal quest_failed(quest_name)
signal step_complete(quest_name)
signal step_updated(quest_name)
signal new_quest_added(quest_name)
signal quest_reset(quest_name)

but, not all the signals are emitted with quest name, for example, step updated contains the step, quest completed sends rewards dictionary.

also on quest completed signal, it says it's emitting the quest name, but it is emitting the id instead.

Thank you for the library it's awesome

**Comment by CValentinTraverso** [comment]
There is another bug, when I set a boolean meta data, it looses its value when loaded in the quest manager window and it always shows as true

**Comment by CValentinTraverso** [comment]
Also, signal step_complete is returning the NEXT step, not the completed one as the name may indicate

**Comment by Chevifier** [comment]
@CValentinTraverso  Sorry for the late response Ill be posting an update soon with these fixes. Also the step_complete data was what I intended but Ill change it so it pases both the completed step_id as well as the next step_id

**Comment by Chevifier** [comment]
All these issue fixed in version 0.8.0 Thanks for this heads up.
