### ISSUE TITLE
Invalid get index 'complete' (on base: 'Dictionary').

### ISSUE THREAD

**Issue by snipercup** [Chevifier/QuestManager#20]
I got this error:

```
Invalid get index 'complete' (on base: 'Dictionary').
```

On this line:
https://github.com/Chevifier/QuestManager/blob/d69764fd853230ae636ddc4dacccc798935dd1ba/addons/quest_manager/QuestManager.gd#L120

I think this happens because the incremental step is the only one that has the `completed` property, while all the others have `complete` property
https://github.com/Chevifier/QuestManager/blob/d69764fd853230ae636ddc4dacccc798935dd1ba/addons/quest_manager/ScriptQuest.gd#L40

I recommend giving the incremental step the `complete` property instead of the `completed` property. The workaround is to manually assign the `complete` property to the step.

This is my stack trace:
![image](https://github.com/Chevifier/QuestManager/assets/50166150/42d616e9-8779-4ac3-b55e-6281f4ffea8b)

This is where I call the `progress_quest` function:
![image](https://github.com/Chevifier/QuestManager/assets/50166150/f72eb557-d52f-4e41-a7ce-51bdd0863f08)

**Comment by Chevifier** [comment]
I'm currently working on a new quest tracking system where much of the setting up on the user side will be simplified. The Editor itself will remain mostly unchanged. You wont be calling progress_quest anymore as each quest will be its own node on the Quest Manager and each quest will hold its current step as its child(That will be of its specific type to track its own data) and communicate back to the questmanager through signals.

**Comment by Chevifier** [comment]
Thanks thats a typo on my part. Ill post a fix soon with other changes

**Comment by Chevifier** [comment]
Fixed with update 0.9.0
